language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

install:
  - composer self-update
  - composer install --prefer-source

script: phpunit

# do not run performance tests as they take too long to run and are killed by Travis
branches:
  except:
    - perf-tests
